#https://plugins.jetbrains.com/plugin/13075-retrofit-rest-client/
POST
http://18.141.132.160/auth/token

# headers
@Content-Type: application/json
@Access-Control-Allow-Origin: "*"

{"username":"bluevinegar","password":"kLMBD4GARf12ThvdWRUn5IjzuXNbF8jav2nXU9ypej"}

%%%
# Duration: 821 ms
# POST
# http://18.141.132.160/auth/token
# Headers
# @Access-Control-Allow-Origin: "*"
# @Content-Type: application/json
# Body
# {"username":"bluevinegar","password":"kLMBD4GARf12ThvdWRUn5IjzuXNbF8jav2nXU9ypej"}


# status 200

@Server: nginx/1.18.0 (Ubuntu)
@Date: Thu, 24 Feb 2022 18:45:00 GMT
@Content-Type: application/json
@Content-Length: 174
@Connection: keep-alive

{
  "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImJsdWV2aW5lZ2FyIiwiZXhwaXJlcyI6MTY0NTgxNDcwMC4yMzE3ODIyfQ.hhSh1FsrPwAsKE8ZFrDiLkAfcudofTpb4a512jAnmHA"
}
